<?php

namespace App\Console\Commands;

use App\Models\TranslationCache;
use Illuminate\Console\Command;

/**
 * Snapshots the live `translations` cache table into the committed data file
 * (database/data/translations.php). Run this after warming translations online
 * so production can then seed them with zero API calls.
 *
 *   php artisan translations:warm --sync   # generate (needs connectivity)
 *   php artisan translations:export        # bake into the committed file
 */
class ExportTranslations extends Command
{
    protected $signature = 'translations:export {--path= : Override output file path}';

    protected $description = 'Export the translations cache into the committed database/data/translations.php file';

    public function handle(): int
    {
        $path = $this->option('path') ?: database_path('data/translations.php');

        // Group cache rows: source string => [locale => translated].
        $grouped = [];
        TranslationCache::orderBy('source_text')->chunk(500, function ($rows) use (&$grouped) {
            foreach ($rows as $row) {
                $grouped[$row->source_text][$row->locale] = $row->translated_text;
            }
        });

        if (empty($grouped)) {
            $this->warn('Translation cache is empty — nothing to export. Run `translations:warm --sync` first (needs connectivity).');
            return self::SUCCESS;
        }

        ksort($grouped);
        foreach ($grouped as &$byLocale) {
            ksort($byLocale);
        }
        unset($byLocale);

        $header = "<?php\n\n"
            . "/*\n"
            . " | Baked translations for seeded DB content — AUTO-GENERATED by `php artisan translations:export`.\n"
            . " | Loaded by TranslationsSeeder into the `translations` cache (no runtime API needed).\n"
            . " | Format: 'English source' => ['sw'=>'…','fr'=>'…','es'=>'…','de'=>'…','zh'=>'…']\n"
            . " */\n\n"
            . "return " . $this->exportArray($grouped) . ";\n";

        @mkdir(dirname($path), 0755, true);
        file_put_contents($path, $header);

        $strings = count($grouped);
        $pairs   = array_sum(array_map('count', $grouped));
        $this->info("Exported {$strings} source strings ({$pairs} translations) to {$path}");

        return self::SUCCESS;
    }

    /** Pretty single-quoted array export (nicer than var_export for committing). */
    protected function exportArray(array $data): string
    {
        $out = "[\n";
        foreach ($data as $source => $byLocale) {
            $pairs = [];
            foreach ($byLocale as $locale => $text) {
                $pairs[] = "'" . addcslashes($locale, "'\\") . "' => '" . addcslashes($text, "'\\") . "'";
            }
            $key = "'" . addcslashes((string) $source, "'\\") . "'";
            $out .= "    {$key} => [" . implode(', ', $pairs) . "],\n";
        }
        $out .= "]";

        return $out;
    }
}
