<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\SafariDestination;
use App\Models\SafariActivity;

class SafariDestinationSeeder extends Seeder
{
    public function run(): void
    {
        $destinations = [
            [
                'name' => 'Serengeti National Park',
                'tagline' => 'Witness the Great Migration',
                'description' => 'The Serengeti is Tanzania\'s oldest and most popular national park, and a world heritage site. Famous for the annual migration of over 1.5 million wildebeest and 250,000 zebra, the park offers arguably the most scintillating game-viewing in Africa. The endless plains span 15,000 square kilometers, offering breathtaking landscapes and incredible predator action.',
                'short_description' => 'Home to the world\'s most spectacular wildlife migration',
                'location' => 'Northern Tanzania',
                'best_time' => 'June - October (Migration), December - March (Calving)',
                'icon' => 'fa-paw',
                'badge' => 'Popular',
                'badge_color' => 'danger',
                'is_featured' => true,
                'display_order' => 1,
                'highlight_1' => 'Great Migration viewing',
                'highlight_2' => 'Big Five encounters',
                'highlight_3' => 'Hot air balloon safaris',
                'area' => '14,763 km²',
                'established' => '1951',
                'wildlife_count' => '4,000+ lions',
                'activities' => [
                    ['name' => 'Game Drives', 'icon' => 'fa-car', 'description' => 'Full-day and half-day safari drives'],
                    ['name' => 'Hot Air Balloon', 'icon' => 'fa-hot-air-balloon', 'description' => 'Sunrise balloon safari with champagne breakfast'],
                    ['name' => 'Walking Safaris', 'icon' => 'fa-walking', 'description' => 'Guided bush walks with rangers'],
                    ['name' => 'Photography Tours', 'icon' => 'fa-camera', 'description' => 'Specialist photography safaris'],
                    ['name' => 'Cultural Visits', 'icon' => 'fa-users', 'description' => 'Maasai village experiences'],
                ]
            ],
            [
                'name' => 'Ngorongoro Crater',
                'tagline' => 'World\'s largest inactive volcano',
                'description' => 'Often called \'Africa\'s Garden of Eden\', the Ngorongoro Crater is the world\'s largest inactive volcanic caldera. This natural wonder is home to approximately 25,000 animals, including the densest known population of lions. The crater\'s walls rise 400-610 meters, creating a self-contained ecosystem with stunning diversity.',
                'short_description' => 'UNESCO World Heritage site with incredible wildlife density',
                'location' => 'Northern Tanzania (Ngorongoro Conservation Area)',
                'best_time' => 'Year-round (best June - October)',
                'icon' => 'fa-mountain',
                'badge' => null,
                'badge_color' => 'secondary',
                'is_featured' => true,
                'display_order' => 2,
                'highlight_1' => 'Highest wildlife density in Africa',
                'highlight_2' => 'Endangered black rhino',
                'highlight_3' => 'Stunning crater views',
                'area' => '260 km²',
                'established' => '1959',
                'wildlife_count' => '25,000+ animals',
                'activities' => [
                    ['name' => 'Crater Game Drives', 'icon' => 'fa-car', 'description' => 'Full-day exploration of the crater floor'],
                    ['name' => 'Crater Rim Walks', 'icon' => 'fa-hiking', 'description' => 'Guided walks along the crater rim'],
                    ['name' => 'Maasai Village Visit', 'icon' => 'fa-users', 'description' => 'Authentic cultural experience'],
                    ['name' => 'Lerai Forest Tracking', 'icon' => 'fa-binoculars', 'description' => 'Elephant and bird watching'],
                    ['name' => 'Olduvai Gorge Tour', 'icon' => 'fa-landmark', 'description' => 'Visit the cradle of mankind'],
                ]
            ],
            [
                'name' => 'Tarangire National Park',
                'tagline' => 'Home to giant elephants',
                'description' => 'Tarangire is famous for its massive elephant herds and iconic baobab trees. During the dry season, the Tarangire River becomes the only water source, attracting enormous concentrations of wildlife. The park offers excellent game viewing with fewer crowds than the northern circuit parks.',
                'short_description' => 'Elephant paradise with iconic baobab landscapes',
                'location' => 'Northern Tanzania (118km from Arusha)',
                'best_time' => 'June - November (Dry season)',
                'icon' => 'fa-tree',
                'badge' => null,
                'badge_color' => 'secondary',
                'is_featured' => false,
                'display_order' => 3,
                'highlight_1' => 'Largest elephant herds in Tanzania',
                'highlight_2' => 'Ancient baobab trees',
                'highlight_3' => 'Excellent bird watching',
                'area' => '2,850 km²',
                'established' => '1970',
                'wildlife_count' => '3,000+ elephants',
                'activities' => [
                    ['name' => 'Game Drives', 'icon' => 'fa-car', 'description' => 'Explore elephant country'],
                    ['name' => 'Walking Safaris', 'icon' => 'fa-walking', 'description' => 'Guided nature walks'],
                    ['name' => 'Bird Watching', 'icon' => 'fa-dove', 'description' => '500+ bird species'],
                    ['name' => 'Night Game Drives', 'icon' => 'fa-moon', 'description' => 'Nocturnal wildlife viewing'],
                    ['name' => 'Fly Camping', 'icon' => 'fa-campground', 'description' => 'Sleep under the stars'],
                ]
            ],
            [
                'name' => 'Lake Manyara',
                'tagline' => 'Tree-climbing lions',
                'description' => 'Nestled at the base of the Rift Valley escarpment, Lake Manyara is a scenic gem. The park is renowned for its unusual tree-climbing lions, vast elephant herds, and the soda lake that attracts thousands of pink flamingos. Its compact size makes it perfect for day trips.',
                'short_description' => 'Scenic park famous for tree-climbing lions',
                'location' => 'Northern Tanzania (126km from Arusha)',
                'best_time' => 'June - October (Dry season)',
                'icon' => 'fa-water',
                'badge' => null,
                'badge_color' => 'secondary',
                'is_featured' => false,
                'display_order' => 4,
                'highlight_1' => 'Famous tree-climbing lions',
                'highlight_2' => 'Thousands of flamingos',
                'highlight_3' => 'Groundwater forest',
                'area' => '330 km²',
                'established' => '1960',
                'wildlife_count' => '400+ bird species',
                'activities' => [
                    ['name' => 'Game Drives', 'icon' => 'fa-car', 'description' => 'Compact park exploration'],
                    ['name' => 'Canoe Safari', 'icon' => 'fa-water', 'description' => 'Paddle on the lake (seasonal)'],
                    ['name' => 'Tree Walk', 'icon' => 'fa-tree', 'description' => 'Elevated walkway through forest'],
                    ['name' => 'Bird Watching', 'icon' => 'fa-binoculars', 'description' => 'Flamingos and pelicans'],
                    ['name' => 'Night Drives', 'icon' => 'fa-moon', 'description' => 'After-dark wildlife viewing'],
                ]
            ],
            [
                'name' => 'Selous Game Reserve',
                'tagline' => 'Africa\'s largest game reserve',
                'description' => 'The Selous is Africa\'s largest game reserve and a UNESCO World Heritage site. Three times larger than the Serengeti, this vast wilderness offers a truly exclusive safari experience. The Rufiji River system creates a unique ecosystem perfect for boat safaris and walking expeditions.',
                'short_description' => 'Untouched wilderness, boat safaris, walking expeditions',
                'location' => 'Southern Tanzania',
                'best_time' => 'June - October',
                'icon' => 'fa-binoculars',
                'badge' => 'Wild',
                'badge_color' => 'warning',
                'is_featured' => true,
                'display_order' => 5,
                'highlight_1' => 'Boat safaris on Rufiji River',
                'highlight_2' => 'Walking safaris permitted',
                'highlight_3' => 'Wild dog viewing',
                'area' => '50,000 km²',
                'established' => '1922',
                'wildlife_count' => 'Largest wild dog population',
                'activities' => [
                    ['name' => 'Boat Safaris', 'icon' => 'fa-ship', 'description' => 'River and lake exploration'],
                    ['name' => 'Game Drives', 'icon' => 'fa-car', 'description' => 'Off-road driving permitted'],
                    ['name' => 'Walking Safaris', 'icon' => 'fa-walking', 'description' => 'Multi-day foot expeditions'],
                    ['name' => 'Fly Camping', 'icon' => 'fa-campground', 'description' => 'Sleep in the wild'],
                    ['name' => 'Fishing', 'icon' => 'fa-fish', 'description' => 'Tiger fish and catfish'],
                ]
            ],
            [
                'name' => 'Ruaha National Park',
                'tagline' => 'Untouched wilderness',
                'description' => 'Tanzania\'s largest national park, Ruaha remains one of the continent\'s best-kept safari secrets. The Great Ruaha River attracts incredible concentrations of wildlife, including 10% of Africa\'s lions. The park offers an authentic, crowd-free wilderness experience.',
                'short_description' => 'Tanzania\'s largest park, remote and wild',
                'location' => 'Central Tanzania',
                'best_time' => 'June - October',
                'icon' => 'fa-safari',
                'badge' => null,
                'badge_color' => 'secondary',
                'is_featured' => false,
                'display_order' => 6,
                'highlight_1' => '10% of Africa\'s lions',
                'highlight_2' => 'Giant baobab forests',
                'highlight_3' => 'Rare antelope species',
                'area' => '20,226 km²',
                'established' => '1964',
                'wildlife_count' => 'Largest elephant herds',
                'activities' => [
                    ['name' => 'Game Drives', 'icon' => 'fa-car', 'description' => 'All-day wilderness drives'],
                    ['name' => 'Walking Safaris', 'icon' => 'fa-walking', 'description' => 'Bush walks with rangers'],
                    ['name' => 'Bird Watching', 'icon' => 'fa-dove', 'description' => '574 bird species'],
                    ['name' => 'Night Drives', 'icon' => 'fa-moon', 'description' => 'Nocturnal predator viewing'],
                    ['name' => 'Cultural Tours', 'icon' => 'fa-users', 'description' => 'Hehe and Barabaig visits'],
                ]
            ],
            [
                'name' => 'Mount Kilimanjaro National Park',
                'tagline' => 'Roof of Africa',
                'description' => 'Mount Kilimanjaro is Africa\'s highest peak and the world\'s tallest free-standing mountain. This UNESCO World Heritage site offers an incredible climbing experience through five distinct climate zones, from tropical rainforest to arctic summit. The mountain is home to unique flora and fauna found nowhere else.',
                'short_description' => 'Africa\'s highest peak - 5,895 meters',
                'location' => 'Northern Tanzania',
                'best_time' => 'January - March, June - October',
                'icon' => 'fa-mountain',
                'badge' => 'Adventure',
                'badge_color' => 'success',
                'is_featured' => true,
                'display_order' => 7,
                'highlight_1' => 'Africa\'s highest peak',
                'highlight_2' => 'Seven climbing routes',
                'highlight_3' => 'Five climate zones',
                'area' => '1,688 km²',
                'established' => '1973',
                'wildlife_count' => 'Unique endemic species',
                'activities' => [
                    ['name' => 'Mountain Climbing', 'icon' => 'fa-hiking', 'description' => '7-day summit expeditions'],
                    ['name' => 'Nature Walks', 'icon' => 'fa-walking', 'description' => 'Forest and moorland hikes'],
                    ['name' => 'Bird Watching', 'icon' => 'fa-dove', 'description' => 'High-altitude bird species'],
                    ['name' => 'Cultural Tours', 'icon' => 'fa-users', 'description' => 'Chagga village visits'],
                    ['name' => 'Photography', 'icon' => 'fa-camera', 'description' => 'Dramatic landscape shots'],
                ]
            ],
            [
                'name' => 'Arusha National Park',
                'tagline' => 'Hidden gem near Mount Meru',
                'description' => 'Often overlooked, Arusha National Park offers diverse landscapes from lush rainforests to alpine deserts. The park is home to Mount Meru, Tanzania\'s second-highest peak, and beautiful Momella Lakes. It\'s perfect for day trips and acclimatization climbs.',
                'short_description' => 'Diverse landscapes with Mount Meru',
                'location' => 'Northern Tanzania (near Arusha)',
                'best_time' => 'Year-round',
                'icon' => 'fa-tree',
                'badge' => null,
                'badge_color' => 'secondary',
                'is_featured' => false,
                'display_order' => 8,
                'highlight_1' => 'Mount Meru climbing',
                'highlight_2' => 'Momella Lakes flamingos',
                'highlight_3' => 'Ngurdoto Crater',
                'area' => '552 km²',
                'established' => '1960',
                'wildlife_count' => '400+ bird species',
                'activities' => [
                    ['name' => 'Game Drives', 'icon' => 'fa-car', 'description' => 'Day game viewing'],
                    ['name' => 'Canoe Safari', 'icon' => 'fa-water', 'description' => 'Momella Lakes paddling'],
                    ['name' => 'Mount Meru Climb', 'icon' => 'fa-hiking', 'description' => '4-day summit climb'],
                    ['name' => 'Walking Safaris', 'icon' => 'fa-walking', 'description' => 'Guided forest walks'],
                    ['name' => 'Bird Watching', 'icon' => 'fa-binoculars', 'description' => 'Waterfowl and forest birds'],
                ]
            ],
            [
                'name' => 'Mikumi National Park',
                'tagline' => 'Gateway to the southern circuit',
                'description' => 'Mikumi is Tanzania\'s fourth-largest national park and the most accessible from Dar es Salaam. The park is bordered by the Uluguru Mountains and offers excellent game viewing with populations of lions, elephants, buffaloes, and the rare African wild dog.',
                'short_description' => 'Accessible park with diverse wildlife',
                'location' => 'Southern Tanzania (283km from Dar)',
                'best_time' => 'June - October',
                'icon' => 'fa-paw',
                'badge' => null,
                'badge_color' => 'secondary',
                'is_featured' => false,
                'display_order' => 9,
                'highlight_1' => 'African wild dog sightings',
                'highlight_2' => 'Easy accessibility from Dar',
                'highlight_3' => 'Uluguru Mountain backdrop',
                'area' => '3,230 km²',
                'established' => '1964',
                'wildlife_count' => 'Diverse big game',
                'activities' => [
                    ['name' => 'Game Drives', 'icon' => 'fa-car', 'description' => 'Full-day safari drives'],
                    ['name' => 'Walking Safaris', 'icon' => 'fa-walking', 'description' => 'Guided bush walks'],
                    ['name' => 'Bird Watching', 'icon' => 'fa-dove', 'description' => '400+ bird species'],
                    ['name' => 'Cultural Tours', 'icon' => 'fa-users', 'description' => 'Local village visits'],
                    ['name' => 'Photography', 'icon' => 'fa-camera', 'description' => 'Wildlife and landscapes'],
                ]
            ],
            [
                'name' => 'Mahale Mountains National Park',
                'tagline' => 'Chimpanzee paradise',
                'description' => 'Mahale Mountains is home to the world\'s largest population of wild chimpanzees. This remote park on the shores of Lake Tanganyika offers a unique combination of primate tracking and beach relaxation. The dramatic mountain backdrop creates a stunning setting for wildlife encounters.',
                'short_description' => 'Best chimpanzee viewing in Africa',
                'location' => 'Western Tanzania (Lake Tanganyika)',
                'best_time' => 'May - October',
                'icon' => 'fa-monkey',
                'badge' => 'Exclusive',
                'badge_color' => 'info',
                'is_featured' => true,
                'display_order' => 10,
                'highlight_1' => '1,000+ chimpanzees',
                'highlight_2' => 'Lake Tanganyika beaches',
                'highlight_3' => 'Remote wilderness',
                'area' => '1,613 km²',
                'established' => '1985',
                'wildlife_count' => 'Largest chimp population',
                'activities' => [
                    ['name' => 'Chimp Tracking', 'icon' => 'fa-binoculars', 'description' => 'Daily chimpanzee treks'],
                    ['name' => 'Forest Hiking', 'icon' => 'fa-hiking', 'description' => 'Mountain trail walks'],
                    ['name' => 'Lake Activities', 'icon' => 'fa-water', 'description' => 'Swimming and snorkeling'],
                    ['name' => 'Fishing', 'icon' => 'fa-fish', 'description' => 'Lake Tanganyika fishing'],
                    ['name' => 'Camping', 'icon' => 'fa-campground', 'description' => 'Beachfront camping'],
                ]
            ],
            [
                'name' => 'Gombe Stream National Park',
                'tagline' => 'Jane Goodall\'s research site',
                'description' => 'Gombe is Tanzania\'s smallest national park but world-famous as the site of Jane Goodall\'s chimpanzee research. The park offers intimate chimpanzee encounters and pristine forest hiking along the shores of Lake Tanganyika.',
                'short_description' => 'Famous chimpanzee research site',
                'location' => 'Western Tanzania (Lake Tanganyika)',
                'best_time' => 'July - October',
                'icon' => 'fa-monkey',
                'badge' => 'Famous',
                'badge_color' => 'success',
                'is_featured' => true,
                'display_order' => 11,
                'highlight_1' => 'Jane Goodall Institute',
                'highlight_2' => 'Habituated chimpanzees',
                'highlight_3' => 'Lake Tanganyika views',
                'area' => '52 km²',
                'established' => '1968',
                'wildlife_count' => '100+ chimpanzees',
                'activities' => [
                    ['name' => 'Chimp Tracking', 'icon' => 'fa-binoculars', 'description' => 'Famous chimp families'],
                    ['name' => 'Forest Walks', 'icon' => 'fa-walking', 'description' => 'Guided nature trails'],
                    ['name' => 'Swimming', 'icon' => 'fa-water', 'description' => 'Lake Tanganyika beaches'],
                    ['name' => 'Bird Watching', 'icon' => 'fa-dove', 'description' => 'Forest bird species'],
                    ['name' => 'Research Tours', 'icon' => 'fa-book', 'description' => 'Learn about conservation'],
                ]
            ],
            [
                'name' => 'Saadani National Park',
                'tagline' => 'Where the bush meets the beach',
                'description' => 'Saadani is unique as the only Tanzanian park bordering the Indian Ocean. This rare combination of wildlife and beach offers game drives in the morning and swimming in the afternoon. The park is home to elephants, lions, and a variety of marine life.',
                'short_description' => 'Only park on the Indian Ocean coast',
                'location' => 'Northern Tanzania (coastal)',
                'best_time' => 'January - February, June - October',
                'icon' => 'fa-umbrella-beach',
                'badge' => 'Unique',
                'badge_color' => 'info',
                'is_featured' => false,
                'display_order' => 12,
                'highlight_1' => 'Beach and bush combination',
                'highlight_2' => 'Marine wildlife',
                'highlight_3' => 'Wami River cruises',
                'area' => '1,100 km²',
                'established' => '2005',
                'wildlife_count' => 'Land and marine species',
                'activities' => [
                    ['name' => 'Game Drives', 'icon' => 'fa-car', 'description' => 'Coastal wildlife viewing'],
                    ['name' => 'Boat Safaris', 'icon' => 'fa-ship', 'description' => 'Wami River cruises'],
                    ['name' => 'Beach Activities', 'icon' => 'fa-umbrella-beach', 'description' => 'Swimming and relaxation'],
                    ['name' => 'Snorkeling', 'icon' => 'fa-water', 'description' => 'Coral reef exploration'],
                    ['name' => 'Green Turtle Watching', 'icon' => 'fa-egg', 'description' => 'Nesting sites (seasonal)'],
                ]
            ],
            [
                'name' => 'Katavi National Park',
                'tagline' => 'Tanzania\'s best-kept secret',
                'description' => 'Katavi is one of Tanzania\'s most remote and untouched parks. During the dry season, the Katuma River attracts massive concentrations of hippos and crocodiles, while the plains fill with thousands of buffalo. It offers a true wilderness experience far from the crowds.',
                'short_description' => 'Remote wilderness with massive wildlife concentrations',
                'location' => 'Western Tanzania',
                'best_time' => 'May - October',
                'icon' => 'fa-hippo',
                'badge' => 'Remote',
                'badge_color' => 'warning',
                'is_featured' => false,
                'display_order' => 13,
                'highlight_1' => 'Largest hippo pods in Africa',
                'highlight_2' => 'Massive buffalo herds',
                'highlight_3' => 'True wilderness experience',
                'area' => '4,471 km²',
                'established' => '1974',
                'wildlife_count' => 'Highest hippo density',
                'activities' => [
                    ['name' => 'Game Drives', 'icon' => 'fa-car', 'description' => 'Exclusive wildlife viewing'],
                    ['name' => 'Walking Safaris', 'icon' => 'fa-walking', 'description' => 'Remote bush walks'],
                    ['name' => 'Bird Watching', 'icon' => 'fa-dove', 'description' => '400+ bird species'],
                    ['name' => 'Fly Camping', 'icon' => 'fa-campground', 'description' => 'Wilderness camping'],
                    ['name' => 'Night Drives', 'icon' => 'fa-moon', 'description' => 'Nocturnal wildlife'],
                ]
            ],
            [
                'name' => 'Rubondo Island National Park',
                'tagline' => 'Island sanctuary in Lake Victoria',
                'description' => 'Rubondo Island is a pristine island sanctuary in Lake Victoria. The park is home to introduced chimpanzees, elephants, and giraffes, alongside native species. It offers a unique combination of forest walks, fishing, and bird watching in a tranquil island setting.',
                'short_description' => 'Island paradise with unique wildlife',
                'location' => 'Northwest Tanzania (Lake Victoria)',
                'best_time' => 'June - August, December - February',
                'icon' => 'fa-water',
                'badge' => 'Tranquil',
                'badge_color' => 'info',
                'is_featured' => false,
                'display_order' => 14,
                'highlight_1' => 'Island chimpanzees',
                'highlight_2' => 'Lake Victoria fishing',
                'highlight_3' => 'Pristine forest',
                'area' => '457 km²',
                'established' => '1977',
                'wildlife_count' => 'Unique island ecosystem',
                'activities' => [
                    ['name' => 'Chimp Tracking', 'icon' => 'fa-binoculars', 'description' => 'Island chimpanzee treks'],
                    ['name' => 'Forest Walks', 'icon' => 'fa-walking', 'description' => 'Guided nature trails'],
                    ['name' => 'Fishing', 'icon' => 'fa-fish', 'description' => 'Nile perch fishing'],
                    ['name' => 'Bird Watching', 'icon' => 'fa-dove', 'description' => '300+ bird species'],
                    ['name' => 'Boat Excursions', 'icon' => 'fa-ship', 'description' => 'Lake Victoria cruises'],
                ]
            ],
            [
                'name' => 'Mkomazi National Park',
                'tagline' => 'Rhino sanctuary',
                'description' => 'Mkomazi is a vital conservation success story, serving as a sanctuary for the endangered black rhino and African wild dog. The park offers stunning views of Mount Kilimanjaro and diverse landscapes from savannah to mountains.',
                'short_description' => 'Black rhino and wild dog sanctuary',
                'location' => 'Northern Tanzania (Kilimanjaro region)',
                'best_time' => 'June - October',
                'icon' => 'fa-shield-alt',
                'badge' => 'Conservation',
                'badge_color' => 'success',
                'is_featured' => false,
                'display_order' => 15,
                'highlight_1' => 'Black rhino breeding program',
                'highlight_2' => 'African wild dog sanctuary',
                'highlight_3' => 'Kilimanjaro views',
                'area' => '3,245 km²',
                'established' => '2006',
                'wildlife_count' => 'Endangered species',
                'activities' => [
                    ['name' => 'Game Drives', 'icon' => 'fa-car', 'description' => 'Rhino and wild dog viewing'],
                    ['name' => 'Walking Safaris', 'icon' => 'fa-walking', 'description' => 'Guided bush walks'],
                    ['name' => 'Bird Watching', 'icon' => 'fa-dove', 'description' => '400+ bird species'],
                    ['name' => 'Cultural Tours', 'icon' => 'fa-users', 'description' => 'Maasai and Pare visits'],
                    ['name' => 'Photography', 'icon' => 'fa-camera', 'description' => 'Kilimanjaro backdrop'],
                ]
            ],
            [
                'name'              => 'Zanzibar Island',
                'slug'              => 'zanzibar',
                'tagline'           => 'Spice Island paradise — turquoise waters, coral reefs, and ancient Stone Town',
                'description'       => 'Zanzibar is a semi-autonomous archipelago off the coast of Tanzania, renowned for its stunning white-sand beaches, crystal-clear turquoise waters, vibrant coral reefs, and the UNESCO World Heritage Site of Stone Town. The island blends African, Arab, Indian, and European influences into a unique cultural tapestry. Beyond the beaches, Zanzibar offers spice tours, dolphin watching, snorkelling, kite-surfing, and exploring the historic alleys of Stone Town. It is the perfect complement to a Tanzania safari — trade your binoculars for a snorkel mask and relax in paradise.',
                'short_description' => 'White beaches, spice tours, and the historic Stone Town — Zanzibar is Tanzania\'s island paradise.',
                'location'          => 'Indian Ocean, Tanzania Coast',
                'best_time'         => 'June – October & December – February',
                'icon'              => 'fa-umbrella-beach',
                'badge'             => 'Beach & Culture',
                'badge_color'       => 'info',
                'is_featured'       => false,
                'is_active'         => true,
                'display_order'     => 16,
                'highlight_1'       => 'UNESCO World Heritage Stone Town',
                'highlight_2'       => 'Pristine Coral Reefs & Marine Parks',
                'highlight_3'       => 'Spice Plantation Tours',
                'area'              => '2,462 km²',
                'established'       => 'Ancient — 10th Century',
                'wildlife_count'    => '200+ Marine Species',
                'activities' => [
                    ['name' => 'Beach Relaxation',      'icon' => 'fa-umbrella-beach', 'description' => 'Relax on world-class white sand beaches like Nungwi and Kendwa'],
                    ['name' => 'Snorkelling & Diving',  'icon' => 'fa-water',          'description' => 'Explore vibrant coral reefs and marine parks'],
                    ['name' => 'Stone Town Tour',        'icon' => 'fa-mosque',         'description' => 'Walk the historic UNESCO World Heritage Site alleys'],
                    ['name' => 'Spice Plantation Tour',  'icon' => 'fa-seedling',       'description' => 'Discover cloves, vanilla, cinnamon, and cardamom'],
                    ['name' => 'Dolphin Watching',       'icon' => 'fa-fish',           'description' => 'Swim with wild dolphins in Kizimkazi Bay'],
                    ['name' => 'Kite Surfing',           'icon' => 'fa-wind',           'description' => 'World-class kite surfing at Paje Beach'],
                    ['name' => 'Deep Sea Fishing',       'icon' => 'fa-anchor',         'description' => 'Game fishing in the Indian Ocean'],
                    ['name' => 'Sunset Dhow Cruise',     'icon' => 'fa-ship',           'description' => 'Traditional wooden dhow sunset cruise with dinner'],
                ],
            ],
        ];

        foreach ($destinations as $destData) {
            $activities = $destData['activities'] ?? [];
            unset($destData['activities']);
            
            $destination = SafariDestination::firstOrCreate(
                ['slug' => \Illuminate\Support\Str::slug($destData['name'])],
                $destData
            );
            
            foreach ($activities as $activity) {
                SafariActivity::firstOrCreate(
                    [
                        'safari_destination_id' => $destination->id,
                        'name' => $activity['name']
                    ],
                    $activity
                );
            }
        }
    }
}
